swagger: "2.0"
info:
    title: Library Service
    description: Service for managing library operations
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /books:
        get:
            tags:
                - books
            summary: items books
            description: Retrieve all books
            operationId: books#items
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/BookResponse'
            schemes:
                - http
        post:
            tags:
                - books
            summary: create books
            description: Create a new book
            operationId: books#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BooksCreateRequestBody'
                    required:
                        - title
                        - author
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/BooksCreateResponseBody'
            schemes:
                - http
    /books/{id}:
        get:
            tags:
                - books
            summary: item books
            description: Retrieve a book by ID
            operationId: books#item
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksItemResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksItemNotFoundResponseBody'
            schemes:
                - http
        put:
            tags:
                - books
            summary: update books
            description: Update an existing book
            operationId: books#update
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: integer
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BooksUpdateRequestBody'
                    required:
                        - title
                        - author
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksUpdateResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksUpdateNotFoundResponseBody'
            schemes:
                - http
        delete:
            tags:
                - books
            summary: delete books
            description: Delete a book by ID
            operationId: books#delete
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: integer
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksDeleteNotFoundResponseBody'
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - books
            summary: Download ./gen/http/openapi.json
            operationId: books#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    BookResponse:
        title: BookResponse
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Voluptatem velit.
            cover:
                type: string
                description: Book cover image URL
                example: Consequatur dolorem dolores quos nulla placeat earum.
            id:
                type: integer
                description: ID of the book
                example: 3906641788350630844
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: Fugiat vitae.
            title:
                type: string
                description: Title of the book
                example: Placeat facilis culpa sed in beatae.
        description: book entity.
        example:
            author: Sint nulla tempore consectetur ut.
            cover: Labore consectetur dolorum sed.
            id: 1016666915469702664
            published_at: Nihil repudiandae voluptas.
            title: Neque qui quidem architecto eum veniam.
    BooksCreateRequestBody:
        title: BooksCreateRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Eos aperiam beatae est.
            cover:
                type: string
                description: Book cover image URL
                example: Dolorem asperiores qui omnis.
            published_at:
                type: string
                description: Published date of the book
                example: Alias deleniti delectus aspernatur et qui.
            title:
                type: string
                description: Title of the book
                example: Est eos nemo voluptas.
        example:
            author: Assumenda autem quibusdam vel numquam praesentium aut.
            cover: Corporis quas.
            published_at: Maiores facilis ducimus quia harum.
            title: Totam incidunt numquam.
        required:
            - title
            - author
    BooksCreateResponseBody:
        title: BooksCreateResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Quo autem beatae quis quaerat.
            cover:
                type: string
                description: Book cover image URL
                example: Exercitationem et et quaerat.
            id:
                type: integer
                description: ID of the book
                example: 4014789084404063380
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: Iusto consequuntur illum ut adipisci reprehenderit.
            title:
                type: string
                description: Title of the book
                example: Quae itaque aut laudantium laborum.
        example:
            author: Quia et doloremque iste tenetur reiciendis.
            cover: Aut consequatur vitae autem ipsa cumque.
            id: 7438356893843391747
            published_at: Autem neque.
            title: Tenetur quae quos voluptas consequuntur distinctio.
    BooksDeleteNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Book not found (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksItemNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Book not found (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksItemResponseBody:
        title: BooksItemResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Et non fugit.
            cover:
                type: string
                description: Book cover image URL
                example: Laudantium molestiae ipsum aut dolores non.
            id:
                type: integer
                description: ID of the book
                example: 8614819544648118412
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: Dicta dolorem voluptatem.
            title:
                type: string
                description: Title of the book
                example: Eos fuga eveniet deserunt dolores provident ipsa.
        example:
            author: Est mollitia minus adipisci consequuntur.
            cover: Ut odio iste odio rerum.
            id: 3202535219662424517
            published_at: Iure aut rerum harum.
            title: In qui quidem.
    BooksUpdateNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Book not found (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksUpdateRequestBody:
        title: BooksUpdateRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Et laboriosam maxime voluptatem magnam.
            cover:
                type: string
                description: Book cover image URL
                example: Molestiae cum facilis et commodi voluptas.
            published_at:
                type: string
                description: Published date of the book
                example: Ea at tempore.
            title:
                type: string
                description: Title of the book
                example: Odio et.
        example:
            author: Voluptas iusto aliquam.
            cover: Et sed perferendis exercitationem vel reiciendis.
            published_at: Qui molestias enim repellat aut.
            title: Ipsum necessitatibus.
        required:
            - title
            - author
    BooksUpdateResponseBody:
        title: BooksUpdateResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Minima dignissimos asperiores.
            cover:
                type: string
                description: Book cover image URL
                example: At qui voluptatibus quas sunt et.
            id:
                type: integer
                description: ID of the book
                example: 4296199374424904704
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: Totam eveniet soluta.
            title:
                type: string
                description: Title of the book
                example: Vel ipsa.
        example:
            author: Sapiente veritatis mollitia quo.
            cover: Aliquam repudiandae voluptatum corrupti et nihil itaque.
            id: 5698593702931980896
            published_at: Autem inventore sunt dolorum aut qui.
            title: Sit laudantium laboriosam consequatur vel.
