swagger: "2.0"
info:
    title: Library Service
    description: Service for managing library operations
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /books:
        get:
            tags:
                - books
            summary: list books
            description: Retrieve all books
            operationId: books#list
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/BookResponse'
            schemes:
                - http
        post:
            tags:
                - books
            summary: create books
            description: Create a new book
            operationId: books#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BooksCreateRequestBody'
                    required:
                        - title
                        - author
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/BooksCreateResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BooksCreateBadRequestResponseBody'
            schemes:
                - http
    /books/{id}:
        get:
            tags:
                - books
            summary: show books
            description: Retrieve a book by ID
            operationId: books#show
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksShowResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksShowNotFoundResponseBody'
            schemes:
                - http
        put:
            tags:
                - books
            summary: update books
            description: Update an existing book
            operationId: books#update
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: integer
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BooksUpdateRequestBody'
                    required:
                        - title
                        - author
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksUpdateResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BooksUpdateBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksUpdateNotFoundResponseBody'
            schemes:
                - http
        delete:
            tags:
                - books
            summary: delete books
            description: Delete a book by ID
            operationId: books#delete
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: integer
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksDeleteNotFoundResponseBody'
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - books
            summary: Download ./gen/http/openapi.json
            operationId: books#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    BookResponse:
        title: BookResponse
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Nihil doloremque autem quae.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id:
                type: integer
                description: ID of the book
                example: 1074672233301932060
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: "2012-03-09"
                format: date
            title:
                type: string
                description: Title of the book
                example: Quae error amet sed.
        description: book entity.
        example:
            author: Accusamus sit.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id: 3172195751037199972
            published_at: "1996-11-17"
            title: Dignissimos illum.
    BooksCreateBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Invalid request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksCreateRequestBody:
        title: BooksCreateRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Quidem consequatur eaque repellendus sit.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            published_at:
                type: string
                description: Published date of the book
                example: "1976-12-20"
                format: date
            title:
                type: string
                description: Title of the book
                example: Est recusandae et quia molestiae molestiae.
        example:
            author: Velit sequi quia quia quibusdam.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            published_at: "1984-03-30"
            title: Sit culpa reiciendis id non.
        required:
            - title
            - author
    BooksCreateResponseBody:
        title: BooksCreateResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Quasi libero est et eius doloremque.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id:
                type: integer
                description: ID of the book
                example: 7065022017253379684
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: "1991-10-31"
                format: date
            title:
                type: string
                description: Title of the book
                example: Doloribus molestiae voluptatum.
        example:
            author: Error repudiandae itaque eos tempore magni.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id: 8055002382332140739
            published_at: "1978-05-10"
            title: Consequatur cupiditate perspiciatis.
    BooksDeleteNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Book not found (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksShowNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Book not found (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksShowResponseBody:
        title: BooksShowResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Eius et aspernatur sunt mollitia.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id:
                type: integer
                description: ID of the book
                example: 882970705699125919
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: "1970-03-12"
                format: date
            title:
                type: string
                description: Title of the book
                example: Numquam sint quis autem dolorem ad dolores.
        example:
            author: Suscipit necessitatibus eveniet dolor.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id: 3161842094744503688
            published_at: "1976-03-13"
            title: Ratione corrupti aspernatur asperiores ex fugit vero.
    BooksUpdateBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Invalid request (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksUpdateNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Book not found (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksUpdateRequestBody:
        title: BooksUpdateRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Maxime et.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            published_at:
                type: string
                description: Published date of the book
                example: "1984-11-24"
                format: date
            title:
                type: string
                description: Title of the book
                example: Est consequatur qui.
        example:
            author: Aperiam quasi.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            published_at: "1991-09-29"
            title: Saepe aut aperiam sint.
        required:
            - title
            - author
    BooksUpdateResponseBody:
        title: BooksUpdateResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Vitae temporibus aut ad qui.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id:
                type: integer
                description: ID of the book
                example: 4153201793639918980
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: "2008-04-17"
                format: date
            title:
                type: string
                description: Title of the book
                example: Iste nostrum.
        example:
            author: Et qui rerum.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id: 3333684133296519941
            published_at: "1974-09-28"
            title: Quibusdam similique dolor iste sunt enim impedit.
